# Generated by Django 4.1.6 on 2023-10-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("password", models.CharField(max_length=255)),
                ("pin", models.CharField(max_length=4, unique=True)),
                ("token", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
