# Generated by Django 4.1.6 on 2023-10-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(default="null", max_length=255),
        ),
    ]
