# Generated by Django 4.2.7 on 2023-12-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_rename_status_order_status_kds"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "table_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("start_time", models.CharField(max_length=255)),
            ],
        ),
    ]
